blog/urls.py
from django.urls import path
from .views import homepage,post_details,post_list, PostListView, post_share, post_list_by_month, PostCreateView, PostUpdateView, PostDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('list/', post_list, name='post_list'),
    # path('list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_details, name='post_details'),
    path('<int:post_id>/share/',post_share, name='post_share'),
    path('profile/', views.profileEdit, name='profile'), 
    path('create/', PostCreateView.as_view(), name='postcreate'),
    # path('post_edit/', PostCreateView.as_view(), name='post_edit'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='postupdate'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='postdelete'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('archive/<int:year>/<int:month>/', post_list_by_month, name='list_by_month'),
    path('my_posts/', views.user_posts, name='my_posts'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls',)),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Profile, Post
from django.contrib.auth.models import User 
from taggit.models import Tag



class EmailPostForm(forms.Form):
    # fields = ('name')
    title = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments =forms.CharField(required=False,
                              widget=forms.Textarea)
    
    # def __init__(self, *args, ** kwargs):
    #     super(EmailPostForm, self).__init__(*args, **kwargs)
    #     self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        
    def __init__(self, *args, ** kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, ** kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})

        
class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'profile_picture')
        
    def __init__(self, *args, ** kwargs):
        super(ProfileEdit, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control', 'placeholder':'YYYY-MM-DD'})
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple)
    # tags = forms.
    class Meta:
        model = Post
        fields = ('title', 'slug', 'body', 'tags', 'image', 'status')      
        widgets = {'slug': forms.HiddenInput(),}
        
    def __init__(self, *args, ** kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['slug'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['status'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['image'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['tags'].widget.attrs.update({'class': 'form-control', 'placeholder':''})

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post, IntroPost
from django.db.models.functions import TruncMonth
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from.models import Profile
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from . forms import ProfileEdit, UserEditForm, PostForm
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.utils.text import slugify
from django.contrib.auth.models import User
from datetime import datetime

# from.models import Profile

# Create your views here.

@login_required(login_url='login')
def homepage(request, tag_slug=None):
    posts =Post.published.all()
    months = Post.objects.filter(status='published').annotate(month=TruncMonth('publish')).values('month').distinct().order_by('-month')

    # intro_posts = IntroPost
    tag = None
    tag_list = Tag.objects.all()
    tag_items = []
    for tag_item in tag_list:
        tag_items.append(tag_item)
        print(tag_item)
    print(tag_items)
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag]) 
    return render(request, 'blog/home.html', {'tag':tag,
                                              'tag_list':tag_list,
                                              'posts':posts,
                                              'months':months,})

@login_required(login_url='login')
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    tag_list = Tag.objects.all()
    
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        
    paginator = Paginator(object_list, 6) # Show 6 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'page':page,
                                                   'tag':tag,
                                                   'tag_list':tag_list,})

@login_required(login_url='login')
def post_details(request, year, month, day, slug):
    posts = get_object_or_404(Post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=slug)
    
    if posts == EmptyPage:
        return homepage
    
    tag = None
    tag_list = Tag.objects.all()
    
    comments = posts.comments.filter(active=True)
    
    new_comment = None
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
            
            # Redirect user back to the post_details page
            
            # latest_post = Post.objects.filter(status='published').latest('publish')
            # year, month, day = latest_post.publish.year, latest_post.publish.month, latest_post.publish.day,
            # latest_post_slug = latest_post.slug
            return redirect('blog:post_details', year=posts.publish.year,
                            month=posts.publish.month, day=posts.publish.day,
                            slug=posts.slug)
          
    else:
        comment_form = CommentForm()
    
    #List of similar posts
    post_tags_ids = posts.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)
    
    posts.views += 1
    posts.save()
    
    context = {
            'posts': posts,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts':similar_posts,
            'tag_list': tag_list,}
    
    return render(request, 'blog/post/details.html', context)

class PostListView(ListView):
    model = Post
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    
@login_required(login_url='login')   
def post_share(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id, status='published')
    
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{user} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{user}'s comments: {cd['comments']}"
            send_mail(subject, message, user.email, [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
    
@login_required(login_url='login')
def post_list_by_month(request, year, month):
    selected_month = datetime.strptime(f'{year}-{month}', '%Y-%m')
    view = "post_list_by_month"
    posts = Post.objects.filter(status='published', publish__year=year, publish__month=month).order_by('-publish')
    paginator = Paginator(posts, 3) # Show 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
        
    context = {
        'posts': posts,
        'page': page,
        'year': year,
        'month': month,
        'view' : view,
        'selected_month': selected_month,
    }
    return render(request, 'blog/post/list.html', context)

@login_required(login_url='login')
def profileEdit(request):

    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None
        messages.warning(request, 'Profile does not exist')

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEdit(instance=request.user.profile,
                                   data=request.POST,
                                   files=request.FILES)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            # print(request.POST['date_of_birth'])
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEdit(instance=request.user.profile)
    
    context = {'user_form':user_form, 'profile_form':profile_form, 'profile':profile }

    return render(request, 'user/profile.html', context)

# @login_required
# def PostCreateView(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post/create.html', {'form': form})


# @login_required
# def PostUpdateView(request, year, month, day, slug):
#     post = get_object_or_404(Post, slug=slug, status='published', publish__year=year, publish__month=month, publish__day=day, author=request.user)
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             form.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'blog/post/edit.html', {'form': form})

class PostCreateView( CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post/post_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_initial(self):
        initial = super().get_initial()
        if 'title' in self.request.GET:
            initial['title'] = self.request.GET['title']
            initial['slug'] = slugify(self.request.GET['title'])
        return initial

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:my_posts')

    # fields = ['title',  'slug', 'body', 'image', 'tags', 'author', 'status']
    template_name = 'blog/post/post_form.html'

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:my_posts')
    template_name = 'blog/post/post_confirm_delete.html'


@login_required(login_url='login')   

blog/templates/user/profile.html
{% extends 'blog/base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}


{% block content %}

<style>
    *{
    margin: 0;
    padding: 0;

}


hr{
    width: 80%;
    margin-left: 5%;
    margin-right: 5%;
}

.hero{
    width: auto;
    padding-left: 100px;
    padding-right: 100px;
}

/* .container{
    border-left: 1px rgb(148, 148, 148);
    border-right: 1px rgb(148, 148, 148);
    padding: 30px;
} */

.column{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
}

/* .wrap{

   
} */

.box{
    width: 20rem;
    height: auto ;
    justify-items: center;
    display: grid;
    padding: 15px;
    margin: 0px, 30px;
    background-color: rgba(190, 255, 254, 0.481);
    box-shadow:2px 2px 4px rgb(214, 214, 214);
    transition: box-shadow 250ms ease-in-out,
                transform 250ms ease-in-out;
    margin-right: 20px;
    margin-top: 20px;
    border-radius: 7px;

}

.box:hover{
    box-shadow:3px 3px 13px rgb(214, 214, 214);
    transform: scale(1.01);
}

.top{
    display: grid;
    grid-template-columns: 1fr 2fr;
    margin-bottom: 10px;
}
 
img{
    width: 150px;
    /* height: 150px; */
    border-radius: 10px;
    border: 1px rgb(135, 135, 135);
}

.info{
    display: grid;
    align-content: baseline;
    margin-top: auto;
    padding-left: 20px;
    justify-items: end;
}

.date{
    padding-bottom: 69px;
}
 
.comments{
    margin-top: 20px;
    text-align: center;
}


</style>

<!-- {% if messages %}
<div class="alert alert-success">
  {% for message in messages %}
    {{ message }}
  {% endfor %}
</div>
{% endif %} -->

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ messages.tags }} alert alert-dismissible fade show">
            {{ message|safe }}
            <a href="" class="btn-close">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </a>
        </li>
        {% endfor %}
    </ul>
{% endif %}

<div class="profile form-container row  align-items-center justify-content-center" style="width: 100%;">
    <div class="row g-4" style="width: 90%; justify-content:center;">
        

        <div class="col-md-5 col-lg-5">
            <h4 class="d-flex justify-content-between align-items-center mb-3">Your Profile</h4>
            <div class="box">
                    <figure class="image">
                        {% if profile.profile_picture %}
                            <img src="{{ profile.profile_picture.url }}" alt="">
                        {% else %}
                            <ul>
                                <li style="text-decoration: none;"><h4>Update your profile picture.</h4></li>
                            </ul>
                        {% endif %}
                    </figure>
                <div class="info">
                    <div class="prop">
                        <h4 class="name">{{ profile.user }} {{profile.user.last_name}}</h4>
                        <p class="email">{{ request.user.email }}</p>
                        <p class="email">{{ profile.date_of_birth }}</p>
                    </div>
                </div>
            </div>

        </div>
        <form action="" method="post" enctype="multipart/form-data" class="row g-3 col-lg-4 align-items-center justify-content-center order-md-last">
            <h5 class="d-flex justify-content-between align-items-center mb-3">Edit your Profile</h5>
            {% csrf_token %}
            {{ user_form }}
            {{ profile_form }}
            <button class="w-50 btn btn-lg btn-primary" type="submit">Save</button>
        </form>
    </div>

    <div class="container">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'blog:homepage' %}" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-muted">List</a></li>
            <li class="nav-item"><a href="{% url 'blog:profile' %}" class="nav-link px-2 text-muted">My profile</a></li>
        </ul>
          <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
        </footer>
      </div>
</div>

{% endblock %}

blog/templates/user/user_posts.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load i18n %}

{% block title %}Create Post{% endblock %}

{% block content %}


<h2>Published Posts</h2>
{% if published_posts %}
    <ul>
    {% for post in published_posts %}
        <li>
            <a href="{% url 'blog:post_details' post.publish.year post.publish.month post.publish.day post.slug %}">{{post.title}}</a>
        </li>

    {% endfor %}
    </ul>
{% else %}
    <p>You have no published posts.</p>
{% endif %}

<h2>Draft Posts</h2>
{% if draft_posts %}
    <ul>
    {% for post in draft_posts %}
        <li><h5>{{ post.title }}</h5></li>
            <a href="{% url 'blog:postdelete'  post.id %}" class="btn btn-danger" style="text-decoration: none;">Delete post</a>
            <a href="{% url 'blog:postupdate' post.id %}" class="btn btn-success">Update post</a>
    {% endfor %}
    </ul>
{% else %}
    <p>You have no draft posts.</p>
{% endif %}

<p></p>
{% endblock %}