blog/urls.py
from django.urls import path
from .views import homepage,post_details,post_list, PostListView, post_share, post_list_by_month, PostCreateView, PostUpdateView, PostDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('list/', post_list, name='post_list'),
    # path('list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_details, name='post_details'),
    path('<int:post_id>/share/',post_share, name='post_share'),
    path('profile/', views.profileEdit, name='profile'), 
    path('create/', PostCreateView.as_view(), name='postcreate'),
    # path('post_edit/', PostCreateView.as_view(), name='post_edit'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='postupdate'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='postdelete'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('archive/<int:year>/<int:month>/', post_list_by_month, name='list_by_month'),
    path('my_posts/', views.user_posts, name='my_posts'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls',)),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Profile, Post
from django.contrib.auth.models import User 
from taggit.models import Tag



class EmailPostForm(forms.Form):
    # fields = ('name')
    title = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments =forms.CharField(required=False,
                              widget=forms.Textarea)
    
    # def __init__(self, *args, ** kwargs):
    #     super(EmailPostForm, self).__init__(*args, **kwargs)
    #     self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        
    def __init__(self, *args, ** kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, ** kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})

        
class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'profile_picture')
        
    def __init__(self, *args, ** kwargs):
        super(ProfileEdit, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control', 'placeholder':'YYYY-MM-DD'})
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple)
    # tags = forms.
    class Meta:
        model = Post
        fields = ('title', 'slug', 'body', 'tags', 'image', 'status')      
        widgets = {'slug': forms.HiddenInput(),}
        
    def __init__(self, *args, ** kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['slug'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['status'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['image'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['tags'].widget.attrs.update({'class': 'form-control', 'placeholder':''})

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post, IntroPost
from django.db.models.functions import TruncMonth
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from.models import Profile
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from . forms import ProfileEdit, UserEditForm, PostForm
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.utils.text import slugify
from django.contrib.auth.models import User
from datetime import datetime

# from.models import Profile

# Create your views here.

@login_required(login_url='login')
def homepage(request, tag_slug=None):
    posts =Post.published.all()
    months = Post.objects.filter(status='published').annotate(month=TruncMonth('publish')).values('month').distinct().order_by('-month')

    # intro_posts = IntroPost
    tag = None
    tag_list = Tag.objects.all()
    tag_items = []
    for tag_item in tag_list:
        tag_items.append(tag_item)
        print(tag_item)
    print(tag_items)
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag]) 
    return render(request, 'blog/home.html', {'tag':tag,
                                              'tag_list':tag_list,
                                              'posts':posts,
                                              'months':months,})

@login_required(login_url='login')
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    tag_list = Tag.objects.all()
    
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        
    paginator = Paginator(object_list, 6) # Show 6 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'page':page,
                                                   'tag':tag,
                                                   'tag_list':tag_list,})

@login_required(login_url='login')
def post_details(request, year, month, day, slug):
    posts = get_object_or_404(Post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=slug)
    
    if posts == EmptyPage:
        return homepage
    
    tag = None
    tag_list = Tag.objects.all()
    
    comments = posts.comments.filter(active=True)
    
    new_comment = None
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
            
            # Redirect user back to the post_details page
            
            # latest_post = Post.objects.filter(status='published').latest('publish')
            # year, month, day = latest_post.publish.year, latest_post.publish.month, latest_post.publish.day,
            # latest_post_slug = latest_post.slug
            return redirect('blog:post_details', year=posts.publish.year,
                            month=posts.publish.month, day=posts.publish.day,
                            slug=posts.slug)
          
    else:
        comment_form = CommentForm()
    
    #List of similar posts
    post_tags_ids = posts.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)
    
    posts.views += 1
    posts.save()
    
    context = {
            'posts': posts,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts':similar_posts,
            'tag_list': tag_list,}
    
    return render(request, 'blog/post/details.html', context)

class PostListView(ListView):
    model = Post
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    
@login_required(login_url='login')   
def post_share(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id, status='published')
    
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{user} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{user}'s comments: {cd['comments']}"
            send_mail(subject, message, user.email, [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
    
@login_required(login_url='login')
def post_list_by_month(request, year, month):
    selected_month = datetime.strptime(f'{year}-{month}', '%Y-%m')
    view = "post_list_by_month"
    posts = Post.objects.filter(status='published', publish__year=year, publish__month=month).order_by('-publish')
    paginator = Paginator(posts, 3) # Show 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
        
    context = {
        'posts': posts,
        'page': page,
        'year': year,
        'month': month,
        'view' : view,
        'selected_month': selected_month,
    }
    return render(request, 'blog/post/list.html', context)

@login_required(login_url='login')
def profileEdit(request):

    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None
        messages.warning(request, 'Profile does not exist')

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEdit(instance=request.user.profile,
                                   data=request.POST,
                                   files=request.FILES)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            # print(request.POST['date_of_birth'])
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEdit(instance=request.user.profile)
    
    context = {'user_form':user_form, 'profile_form':profile_form, 'profile':profile }

    return render(request, 'user/profile.html', context)

# @login_required
# def PostCreateView(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post/create.html', {'form': form})


# @login_required
# def PostUpdateView(request, year, month, day, slug):
#     post = get_object_or_404(Post, slug=slug, status='published', publish__year=year, publish__month=month, publish__day=day, author=request.user)
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             form.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'blog/post/edit.html', {'form': form})

class PostCreateView( CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post/post_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_initial(self):
        initial = super().get_initial()
        if 'title' in self.request.GET:
            initial['title'] = self.request.GET['title']
            initial['slug'] = slugify(self.request.GET['title'])
        return initial

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:my_posts')

    # fields = ['title',  'slug', 'body', 'image', 'tags', 'author', 'status']
    template_name = 'blog/post/post_form.html'

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:my_posts')
    template_name = 'blog/post/post_confirm_delete.html'


@login_required(login_url='login')   

blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Large | {% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/blog/">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
     integrity="sha512-XeJ+I4R4fQ0m0gY4k4m/sx+Vi1JB3H/hhBnS9JL+kzlzRknIj2NKlY4cJg4xHbBS+K+mGJLdWt9M2OFJ5nG/g==" 
     crossorigin="anonymous" referrerpolicy="no-referrer" />
    

    

    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-margin{
        margin-bottom: 10px;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      .logo{
        font-weight: light;
        padding: 7px 0 7px 0;
        justify-self: center;
        color: white;
        margin-right: 10px;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'blog.css' %}" rel="stylesheet">
    <link href="{% static 'blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <h3 class="logo">
          <a href="#" style="text-decoration: none; color: white;"> Blog</a>
        </h3>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">         
            <li class="nav-item"><a href="{% url 'blog:homepage' %}" class="nav-link px-2">Dashboard</a></li>
            <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2">List</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Personal
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'blog:profile' %}">My Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:my_posts' %}">My Posts</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:postcreate' %}">New Post</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

  
</div>

<main class="container" style="margin-top:5rem;">

  <div class="row g-5">
    <div class="col-md-12">

      {% block content %}

      {% endblock %}

    </div>


  </div>

</main>

{% block javascript %}
    <script src="{% static '/assets/dist/js/bootstrap.bundle.min.js' %}"></script>
{% endblock %}

  </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Home{% endblock %}

{% block content %}

<style>
  .tag-list{
    text-decoration: none;
    color: rgb(83, 83, 83);
    text-transform: capitalize;
    font-weight: 700;
  }

  .banner{
    height: 40%;
    /* justify-content: center;  */
    display: grid; 
    align-content: end;
  }

  .tag-cover{
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    gap: 10px;
    padding: 100px;
  }

  .custom-nav{
  }
  
  /* .banner-content{

  } */
</style>

<div class="nav-scroller py-1 mb-2">
  <nav class="nav d-flex justify-content-between custom-nav">
    <h4>Tags:</h4>
    <div class="tag-cover">
      {% for tag in tag_list %}
      <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="tag-list">
          {{ tag.name }}
      </a>
      {% if not forloop.last %} ,{% endif %}
      {% endfor %}
    </div>
    <a href="{% url 'logout' %}">
      <button type="button" class="btn btn-danger">Log-out</button>
    </a>
  </nav>
</div>

{% get_most_viewed_posts as most_viewed_posts %}
{% for post in most_viewed_posts %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark banner" style="background-size: cover; background-position: center; background-image: url({{ post.image.url }});">
    <div class="col-md-8 px-0 banner-content" >
      {% if request.user.is_authenticated %}
      <h3>Hello {{ request.user }}</h3>
      {% endif %}
      <h4>Join the dicussion on our most viewed post.</h4>
      <h2>Most viewed posts</h2>
      <ul>
          <a href="{{ post.get_absolute_url }}" style="text-decoration: none ; color: white;">
            {{ post.title }}
          </a>
        </ul>
    </div>
</div>
{% endfor %}





<main class="container">

  <div class="row g-5">
    <div class="col-md-8">
      {% show_latest_posts 3 %}

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">
          <h4 class="fst-italic">About the site</h4>
          <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
          <a href="#">Learn more</a>
        </div>

        <div class="p-4">
          <h4> <i class="fas fa-calendar"></i></h4>
          <ol class="list-unstyled mb-0">
            <!-- <h4>This is my archive:</h4> -->
            {% for month in months %}
                <li>
                    <a href="{% url 'blog:list_by_month' month.month|date:'Y' month.month|date:'m' %}">
        
                        {{month.month|date:"F Y"}}
                    </a>
                </li>
            {% endfor %}
          </ol>
        </div>

        <div class="p-4">
          <h4 class="fst-italic">Elsewhere</h4>
          <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ol>
        </div>

        <div class="container">
          <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
              <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-muted">List</a></li>
              <li class="nav-item"><a href="{% url 'blog:profile' %}" class="nav-link px-2 text-muted">My profile</a></li>
              <li class="nav-item"><a href="{% url 'blog:postcreate' %}" class="nav-link px-2 text-muted">New post</a></li>
              <li class="nav-item"><a href="{% url 'blog:my_posts' %}" class="nav-link px-2 text-muted">My posts</a></li>
            </ul>
            <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
          </footer>
        </div>
      </div>
    </div>
  </div>

</main>

{% endblock %}