blog/urls.py
from django.urls import path
from .views import homepage,post_details,post_list, PostListView, post_share, post_list_by_month, PostCreateView, PostUpdateView, PostDeleteView
from . import views

app_name = 'blog'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('list/', post_list, name='post_list'),
    # path('list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', post_details, name='post_details'),
    path('<int:post_id>/share/',post_share, name='post_share'),
    path('profile/', views.profileEdit, name='profile'), 
    path('create/', PostCreateView.as_view(), name='postcreate'),
    # path('post_edit/', PostCreateView.as_view(), name='post_edit'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='postupdate'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='postdelete'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('archive/<int:year>/<int:month>/', post_list_by_month, name='list_by_month'),
    path('my_posts/', views.user_posts, name='my_posts'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls',)),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Profile, Post
from django.contrib.auth.models import User 
from taggit.models import Tag



class EmailPostForm(forms.Form):
    # fields = ('name')
    title = forms.CharField(max_length=25)
    # email = forms.EmailField()
    to = forms.EmailField()
    comments =forms.CharField(required=False,
                              widget=forms.Textarea)
    
    # def __init__(self, *args, ** kwargs):
    #     super(EmailPostForm, self).__init__(*args, **kwargs)
    #     self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        
    def __init__(self, *args, ** kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
        
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, ** kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder':'example@email.com'})

        
class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'profile_picture')
        
    def __init__(self, *args, ** kwargs):
        super(ProfileEdit, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget.attrs.update({'class': 'form-control', 'placeholder':'YYYY-MM-DD'})
        self.fields['profile_picture'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        
class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.SelectMultiple)
    # tags = forms.
    class Meta:
        model = Post
        fields = ('title', 'slug', 'body', 'tags', 'image', 'status')      
        widgets = {'slug': forms.HiddenInput(),}
        
    def __init__(self, *args, ** kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['slug'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['status'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['image'].widget.attrs.update({'class': 'form-control', 'placeholder':''})
        self.fields['tags'].widget.attrs.update({'class': 'form-control', 'placeholder':''})

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post, IntroPost
from django.db.models.functions import TruncMonth
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from.models import Profile
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from . forms import ProfileEdit, UserEditForm, PostForm
from django.utils import timezone
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django import forms
from django.utils.text import slugify
from django.contrib.auth.models import User
from datetime import datetime

# from.models import Profile

# Create your views here.

@login_required(login_url='login')
def homepage(request, tag_slug=None):
    posts =Post.published.all()
    months = Post.objects.filter(status='published').annotate(month=TruncMonth('publish')).values('month').distinct().order_by('-month')

    # intro_posts = IntroPost
    tag = None
    tag_list = Tag.objects.all()
    tag_items = []
    for tag_item in tag_list:
        tag_items.append(tag_item)
        print(tag_item)
    print(tag_items)
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag]) 
    return render(request, 'blog/home.html', {'tag':tag,
                                              'tag_list':tag_list,
                                              'posts':posts,
                                              'months':months,})

@login_required(login_url='login')
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    tag_list = Tag.objects.all()
    
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
        
    paginator = Paginator(object_list, 6) # Show 6 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.get_page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts,
                                                   'page':page,
                                                   'tag':tag,
                                                   'tag_list':tag_list,})

@login_required(login_url='login')
def post_details(request, year, month, day, slug):
    posts = get_object_or_404(Post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=slug)
    
    if posts == EmptyPage:
        return homepage
    
    tag = None
    tag_list = Tag.objects.all()
    
    comments = posts.comments.filter(active=True)
    
    new_comment = None
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
            
            # Redirect user back to the post_details page
            
            # latest_post = Post.objects.filter(status='published').latest('publish')
            # year, month, day = latest_post.publish.year, latest_post.publish.month, latest_post.publish.day,
            # latest_post_slug = latest_post.slug
            return redirect('blog:post_details', year=posts.publish.year,
                            month=posts.publish.month, day=posts.publish.day,
                            slug=posts.slug)
          
    else:
        comment_form = CommentForm()
    
    #List of similar posts
    post_tags_ids = posts.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)
    
    posts.views += 1
    posts.save()
    
    context = {
            'posts': posts,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'similar_posts':similar_posts,
            'tag_list': tag_list,}
    
    return render(request, 'blog/post/details.html', context)

class PostListView(ListView):
    model = Post
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    
@login_required(login_url='login')   
def post_share(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id, status='published')
    
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{user} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{user}'s comments: {cd['comments']}"
            send_mail(subject, message, user.email, [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
    
@login_required(login_url='login')
def post_list_by_month(request, year, month):
    selected_month = datetime.strptime(f'{year}-{month}', '%Y-%m')
    view = "post_list_by_month"
    posts = Post.objects.filter(status='published', publish__year=year, publish__month=month).order_by('-publish')
    paginator = Paginator(posts, 3) # Show 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
        
    context = {
        'posts': posts,
        'page': page,
        'year': year,
        'month': month,
        'view' : view,
        'selected_month': selected_month,
    }
    return render(request, 'blog/post/list.html', context)

@login_required(login_url='login')
def profileEdit(request):

    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None
        messages.warning(request, 'Profile does not exist')

    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEdit(instance=request.user.profile,
                                   data=request.POST,
                                   files=request.FILES)
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            # print(request.POST['date_of_birth'])
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEdit(instance=request.user.profile)
    
    context = {'user_form':user_form, 'profile_form':profile_form, 'profile':profile }

    return render(request, 'user/profile.html', context)

# @login_required
# def PostCreateView(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post/create.html', {'form': form})


# @login_required
# def PostUpdateView(request, year, month, day, slug):
#     post = get_object_or_404(Post, slug=slug, status='published', publish__year=year, publish__month=month, publish__day=day, author=request.user)
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)
#         if form.is_valid():
#             form.save()
#             return redirect('blog:post_details', year=post.publish.year, month=post.publish.month, day=post.publish.day, slug=post.slug)
#     else:
#         form = PostForm(instance=post)
#     return render(request, 'blog/post/edit.html', {'form': form})

class PostCreateView( CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')
    template_name = 'blog/post/post_form.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def get_initial(self):
        initial = super().get_initial()
        if 'title' in self.request.GET:
            initial['title'] = self.request.GET['title']
            initial['slug'] = slugify(self.request.GET['title'])
        return initial

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:my_posts')

    # fields = ['title',  'slug', 'body', 'image', 'tags', 'author', 'status']
    template_name = 'blog/post/post_form.html'

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:my_posts')
    template_name = 'blog/post/post_confirm_delete.html'


@login_required(login_url='login')   

blog/templates/blog/post/details.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}

<style>
  .comments{
    margin-bottom: 1rem;
  }

  .post-body{
    margin-top: 3rem;
  }

  .details{
    color: #fff;
  }
</style>

{% block content %}

<main class="container">

    <div class="row g-5">
      <div class="col-md-8">

        <div class="title">
          <h1>{{ posts.title }}</h1>
          {% if posts.image %}
          <figure class="head-image">
            <img src="{{ posts.image.url }}" alt="" style="width: 60%;" class="rounded-4 shadow">
          </figure>
          {% endif %}
          <p class="date">
              Published {{ posts.publish }} by {{ posts.author }}
          </p>
        </div>
        <div class="post-body" style="margin-top: 3rem;
        ">
          {{ posts.body|safe }}
        </div>
    
        <p>
            <a href="{% url 'blog:post_share' posts.id %}">Share post</a>
            Share this post
            </a>
        </p>
        <br>
        <h2>Similar posts</h2>
        {% for post in similar_posts %}
            {% if post.title != posts.title %}
            <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
            {% endif %}
            {% empty %}
            There are no similar posts yet.
        {% endfor %}
    
        <br>
        {% with comments.count as total_comments %}
            <h2>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h2>
        {% endwith %}
    
    
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
            {% else %}
            <h2>Add a new comment</h2>
            <form method="post" style="width: 70%;">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <button class=" btn btn-sm btn-primary mb-3" type="submit" href>Add comment</button>
            </form>
        {% endif %}
    
        <br>
        
        <div class="list-group w-auto">
          <h5>Comments</h5>
          {% for comment in comments %}
          <div href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3 rounded comments" style="margin-bottom: 1rem; width: 80%;" aria-current="true">
            <div class=" text-center">
              <a class="text-dark" href="#">Large</a>
            </div>
              <div class="d-flex gap-2 w-100 justify-content-between">
              <div>
                <h6 class="mb-0">{{ comment.name }}</h6>
                <p class="mb-0 opacity-75">{{ comment.body|linebreaks }}</p>
              </div>
              <small class="opacity-50 text-nowrap">{{ comment.created|timesince}} ago</small>
            </div>
          </div>
          {% empty %}
          <p>There are no comments yet.</p>
          {% endfor %}
        </div>

        <br>

      </div>
  
      <div class="col-md-4">
        <div class="position-sticky" style="top: 2rem;">
          <div class="border-bottom">
            <div class="p-4 mb-3 bg-light rounded shadow">
              <h4 class="fst-italic">The Author: {{ posts.author }}</h4>
              <p class="mb-0">{{post.authors_comment}}</p>
            </div>
          </div>
          <br> 
          <div class="p-4 mb-3 bg-light rounded shadow">
            <h4 class="fst-italic">Details</h4>

            <ul class="details">
              <li>Author: {{ posts.author }}</li>
              <li>Date: {{ posts.created }}</li>
              <li>Views: {{ posts.views }}</li>
              <li>Tags: 
                {% for tag in tag_list %}
                    {{ tag.name }}
                    {% if not forloop.last %} ,{% endif %}

                {% endfor %}
              </li>
            </ul>
            
          </div>

          <div class="p-4">
            <h4 class="fst-italic">Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
  
          <div class="container">
            <footer class="py-3 my-4">
              <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="{% url 'blog:homepage' %}" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
                <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-muted">List</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
              </ul>
              <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  
  </main>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<style>
  figure{
    display: grid;
    align-content: center;
    height: 100%;
  }
  .tag{
    text-decoration: none;
    color:#858585;
  }
  .tag:hover{
    color:#575757;
  }
</style>

<div class="row">
      
    <h3>
      Latest Posts:
    </h3>
    {% for post in latest_posts %}
    <div class="col-md-9">
      
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">
            <p>
                Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="tag" style="text-decoration: none; color:#858585;">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
        
                {% endfor %}
            </p>
          </strong>
          <a href="{{ post.get_absolute_url }}" class="" style="text-decoration: none; color: inherit;">
            <h3 class="mb-0">{{post.title}}</h3>
          </a>
          <div class="mb-1 text-muted">{{ post.created }}</div>
          {% if post.body %}
          <p class="card-text mb-auto">{{ post.body|truncatewords:7|linebreaks|safe }}</p>
          {% endif %}
        </div>
        <div class="col-auto d-none d-lg-block">
          {% if post.image %}

          <a href="{{ post.get_absolute_url }}" class="" style="text-decoration: none; color: inherit;">
            <figure class="" style=" background-image: url({{ post.image.url }});">
                <img src="{{ post.image.url }}" alt="{{ post.title }}" style="width: 17rem;">
            </figure>
          </a>
          {% endif %}

        </div>
      </div>
    </div>
    {% endfor %}
</div>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

<style>
  .page-butt{
      padding: 5px;
      border: 2px solid darkgray;
      border-radius: 5px;
      text-decoration: none;
      color: #6f6f6f;
  }
  .page-butt:hover{
      color: #4e4e4e;
  }
</style>

{% block title %}List{% endblock %}

<link rel="stylesheet" href="{% static 'features.css' %}">
{% block content %}

{% if view == "post_list_by_month" %}

  <h1>Posts for {{ selected_month|date:"M Y" }}</h1>


{% endif %}

<div class="container px-4 py-5" id="custom-cards">
    <h4 class="pb-2 border-bottom">Thanks to the creators, we have {% total_posts %} posts so far.</h4>
    
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      {% for post in posts %}
      <div class="col" style="margin-bottom: 1.5rem;">
        {% if post.image %}
        <div style="border: none; background-size: cover; background-position: center; background-image: url({{ post.image.url }});" class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
            <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
              <a href="{% url 'blog:post_details' post.publish.year post.publish.month post.publish.day post.slug %}" style=" text-shadow:2px 1px 4px #a1a1a1; text-decoration: none; color: white;">{{post.title}}</a>
            </h2>
            <ul class="d-flex list-unstyled mt-auto">
              <li class="me-auto">
                <p>{{post.author}}</p>
              </li>
              <li class="d-flex align-items-center me-3">
                <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                <small>
                  <p>
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="text-decoration: none; color: rgb(255, 255, 255);">
                            {{ tag.name }}  
                        </a>
                        {% if not forloop.last %} ,{% endif %}
            
                    {% endfor %}
                </p>
                </small>
              </li>
              <li class="d-flex align-items-center">
                  <!-- <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg> -->
                  <!-- <small class="fas fa-calender" style="text-shadow:1px 2px #5a5a5a;">{{ post.created|date:"d M" }}</small> -->
                  <small>{{ post.created|date }}</small>
                </li>
              </ul>
          </div>
        </div>
          {% else %}
          <div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">

            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
        
                <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
                  <a href="{% url 'blog:post_details' post.publish.year post.publish.month post.publish.day post.slug %}" style="text-decoration: none; color: white;">{{post.title}}</a>
                </h2>
                <ul class="d-flex list-unstyled mt-auto">
                  <li class="me-auto">
                    <p>{{post.author}}</p>
                  </li>
                  <li class="d-flex align-items-center me-3">
                    <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
                    <small>
                      <p>
                        {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="text-decoration: none; color: rgb(255, 255, 255);">
                                {{ tag.name }}
                            </a>
                            {% if not forloop.last %} ,{% endif %}
                            
                        {% endfor %}  
                    </p>
                    </small>
                  </li>
                  <li class="d-flex align-items-center">
                      <!-- <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg> -->
                      <small >{{ post.created|date }}</small>
                    </li>
                  </ul>
              </div>
        
        </div>
          {% endif %}
      </div>
      {% endfor %}
    </div>

    <div class="container">
      <div class="pagination">
        {% include "blog/post/pagination.html" with page=posts %}
      </div>

    </div>

    <div class="container">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="{% url 'blog:homepage' %}" class="nav-link px-2 text-muted">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
          <li class="nav-item"><a href="{% url 'blog:post_list' %}" class="nav-link px-2 text-muted">List</a></li>
          <li class="nav-item"><a href="{% url 'blog:profile' %}" class="nav-link px-2 text-muted">My profile</a></li>
        </ul>
        <p class="text-center text-muted">&copy; 2022 Company, Inc</p>
      </footer>
    </div>
</div>


{% endblock %}

blog/templates/blog/post/list_by_month.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>Posts for {{ date:"M Y" }}</h1>

  <ul>
    {% for post in posts %}
      <li>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
        <small class="text-muted">
          {{ post.publish|date:"M d, Y" }}
        </small>
      </li>
    {% empty %}
      <li>No posts found.</li>
    {% endfor %}
  </ul>

  <hr>

  
  <div class="container">
    <div class="pagination">
      {% include "blog/post/pagination.html" with page=posts %}
    </div>

  </div>


{% endblock %}

blog/templates/blog/post/most_viewed_posts.html
<h2>Most viewed posts</h2>
<ul>
{% get_most_viewed_posts as popular_posts %}
{% for post in popular_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>

blog/templates/blog/post/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load i18n %}

{% block title %}Create Post{% endblock %}

{% block content %}

<h1>{% trans 'Delete post' %}</h1>
<p>{% trans 'Are you sure you want to delete this post?' %}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">{% trans 'Yes, delete' %}</button>
    <a href="{% url 'blog:my_posts' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
</form>

{% endblock %}

blog/templates/blog/post/scrap.html
<div class="card card-cover h-100 overflow-hidden text-white bg-dark rounded-4 shadow-lg" style="background-image: url('unsplash-photo-1.jpg');">

    <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">

        <h2 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">
          <a href="{% url 'blog:post_details' post.publish.year post.publish.month post.publish.day post.slug %}" style="text-decoration: none; color: white;">{{post.title}}</a>
        </h2>
        <ul class="d-flex list-unstyled mt-auto">
          <li class="me-auto">
            <p>{{post.author}}</p>
          </li>
          <li class="d-flex align-items-center me-3">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
            <small>
              <p>
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" style="text-decoration: none; color: rgb(255, 255, 255);">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %} ,{% endif %}
        
                {% endfor %}
            </p>
            </small>
          </li>
          <li class="d-flex align-items-center">
              <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
              <small>{{ post.created|date }}</small>
            </li>
          </ul>
      </div>

</div>